version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip3 install requests
      - pip3 install pyjwt
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -g deployment_package.zip lambda_function.py response.py env
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name RetroPixel --zip-file fileb://deployment_package.zip
      - echo "DONE!!"